export default {
  LOAD_MYCOURSES_REQ: "LOAD_MYCOURSES_REQ",
  LOAD_MYCOURSES_SUCCESS: "LOAD_MYCOURSES_SUCCESS",
  LOAD_MYCOURSES_FAILURE: "LOAD_MYCOURSES_FAILURE",

  LOAD_UPCOMING_LESSIONS_REQ: "LOAD_UPCOMING_LESSIONS_REQ",
  LOAD_UPCOMING_LESSIONS_SUCCESS: "LOAD_UPCOMING_LESSIONS_SUCCESS",
  LOAD_UPCOMING_LESSIONS_FAILURE: "LOAD_UPCOMING_LESSIONS_FAILURE",

  LOAD_TASKS_REQ: "LOAD_TASKS_REQ",
  LOAD_TASKS_SUCCESS: "LOAD_TASKS_SUCCESS",
  LOAD_TASKS_FAILURE: "LOAD_TASKS_FAILURE",

  LOAD_GRAPH_DATA_REQ: "LOAD_GRAPH_DATA_REQ",
  LOAD_GRAPH_DATA_SUCCESS: "LOAD_GRAPH_DATA_SUCCESS",
  LOAD_GRAPH_DATA_FAILURE: "LOAD_GRAPH_DATA_FAILURE",

  LOAD_LEADERBOARD_REQ: "LOAD_LEADERBOARD_REQ",
  LOAD_LEADERBOARD_SUCCESS: "LOAD_LEADERBOARD_SUCCESS",
  LOAD_LEADERBOARD_FAILURE: "LOAD_LEADERBOARD_FAILURE",
}
